SCRAPE_TYPE: '4' # use either ALL or number of pages to scrape in string (most recent n pages)
TABLE_SCHEMA: 'recipes_db'
TABLE_NAME: 'recipes'
RETRIEVE_N: 5 # for recipe reco
RANDOMNESS: 'all' # all, new, mix